site_name: Python Camunda SDK
theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.tabs
    - content.code.annotate
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      title: On this page
  - pymdownx.snippets:
      base_path: "docs/snippets"
  - tables
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - index.md
  - Quick start:
    - quick_start/outbound_connectors.md
    - quick_start/generate_template.md
    - quick_start/setup_runtime.md
    - quick_start/using_templates.md
    - quick_start/inbound_connectors.md