site_name: Python Camunda SDK
repo_url: https://github.com/mdelmans/python-camunda-sdk
repo_name: mdelmans/python-camunda-sdk
theme:
  name: "material"
  logo: img/pycam.svg
  favicon: img/pycam.svg
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: pycam
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - content.code.annotate
    - navigation.footer
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      title: On this page
  - pymdownx.snippets:
      base_path: "docs/snippets"
  - tables
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings

nav:
  - About: index.md
  - Quick start:
    - quick_start/index.md
    - Outbound connectors:
      - quick_start/outbound_connectors.md
      - quick_start/generate_outbound_template.md
    - quick_start/setup_runtime.md
    - quick_start/using_templates.md
    - Inbound connectors:
      - quick_start/inbound_connectors.md
      - quick_start/generate_inbound_template.md
  - API:
    - api/connectors.md